blank_issues_enabled: false
contact_links:
  - name: Help & Support
    url: https://github.com/cratespace/sentinel/issues
    about: 'Ask questions and get help by opening up an issue on our repository.'
